export default [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    password: '12345',
    email: 'johndoe@gmail.com',
    type: 'Client',
    isAdmin: false,
  },
  {
    id: 2,
    firstName: '  Mack',
    lastName: 'Doe',
    password: '12345',
    email: 'mackdoe@gmail.com',
    type: 'Staff',
    isAdmin: true,
  },
  {
    id: 3,
    firstName: 'Donald',
    lastName: 'Trump',
    password: '12345',
    email: 'donaldtrump@gmail.com',
    type: 'Staff',
    isAdmin: false,
  },
  {
    id: 4,
    firstName: 'James',
    lastName: 'Doe',
    password: '12345',
    email: 'jamesdoe@gmail.com',
    type: 'Client',
    isAdmin: false,
  },
];
